sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.8
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/protobuf
before_install:
  - bash bin/install-protobuf.sh
  - export PATH=$PATH:$HOME/protobuf/bin
