
get:
  description: Get info about the Metronome Instance
  responses:
    200:
      description: General configuration and runtime information about this Metronome instance.
      body:
        application/json:
          example: !include examples/info.json
