
get:
  description: Get metrics data from this Metronome instance
  responses:
    200:
      description: All aggregated runtime metrics for this Metronome instance.
      body:
        application/json:
          example: |
            {
              "counters": {
                "name.of.counter": {
                  "count": 1
                }
              },
              "gauges": {
                "name.of.gauge": {
                  "value": 7248,
                  "max": 0,
                  "mean": 0.0,
                  "min": 0,
                  "p50": 0.0,
                  "p75": 0.0,
                  "p95": 0.0,
                  "p98": 0.0,
                  "p99": 0.0,
                  "p999": 0.0,
                }
              },
              "histograms": {
                "name.of.histogram": {
                  "count": 0,
                  "max": 0,
                  "mean": 0.0,
                  "min": 0,
                  "p50": 0.0,
                  "p75": 0.0,
                  "p95": 0.0,
                  "p98": 0.0,
                  "p99": 0.0,
                  "p999": 0.0,
                  "stddev": 0.0
                }
              },
              "min-max-counters": {
                "name.of.min-max-counter": {
                  "count": 549,
                  "min": 0,
                  "max": 0,
                  "p50": 0,
                  "p75": 0,
                  "p98": 0,
                  "p99": 0,
                  "p999": 0,
                  "mean": 0
                }
              },
              "system-metric": {
                "name.of.jvm.metric": {
                  "count": 18,
                  "min": 0,
                  "max": 67584,
                  "p50": 2048,
                  "p75": 4096,
                  "p98": 67584,
                  "p99": 67584,
                  "p999": 67584,
                  "mean": 7509.33349609375,
                  "tags": { },
                  "unit": {
                    "name": "bytes",
                    "label": "b"
                  }
                }
              },
              "start": "2018-03-15T09:49:03.975Z",
              "end": "2018-03-15T09:49:03.975Z",
            }
